# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"h3.libh3.experimentalH3ToLocalIj.restype": "00_core.ipynb",
         "h3.libh3.experimentalH3ToLocalIj.argtypes": "00_core.ipynb",
         "local_ij_delta": "00_core.ipynb",
         "local_ij_delta_to_class": "00_core.ipynb",
         "coordinatesToH3IndexSequence": "00_core.ipynb",
         "window": "00_core.ipynb",
         "generate_sequences_with_next_hex_class": "00_core.ipynb",
         "generate_sequences_with_next_hex_class_from_path": "00_core.ipynb",
         "parse_strava_gpx": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://jaredwinick.github.io/h3_sequence/"

git_url = "https://github.com/jaredwinick/h3_sequence/tree/master/"

def custom_doc_links(name): return None
